import os
import json
import re
from datetime import datetime

def slugify(text):
    return re.sub('[^a-zA-Z0-9_-]', '', text.replace(" ", "-").lower())[:32]

def main():
    today = datetime.now().strftime('%Y-%m-%d')
    target = os.environ.get("AGENT_TARGET", "unknown-repo")
    depth = os.environ.get("AGENT_DEPTH", "Atomic")
    tools = os.environ.get("AGENT_TOOLS", "")
    intent = os.environ.get("AGENT_INTENT", "general-investigation")
    clues = os.environ.get("AGENT_CLUES", "")
    issue_number = os.environ.get("ISSUE_NUMBER", "1")

    tool_list = [x.strip() for x in tools.split(",") if x.strip()]

    subject_slug = slugify(target.split('/')[-1]) or 'unknown'
    intent_slug = slugify(intent) or 'unknown'

    artifacts = []
    artifact_map = {
        "Level 1: Hard Architecture Mapping": f"analyses/{subject_slug}/{today}-hard-architecture-mapping.md",
        "Level 2: Decision Forensics": f"atomic/{subject_slug}/{today}-decision-forensics.md",
        "Level 2: Anti-Library Extraction": f"atomic/{subject_slug}/{today}-anti-library.md",
        "Level 3: Vision Alignment": f"atomic/{subject_slug}/{today}-vision-alignment.md",
        "Level 3: Process Memory": f"process_memory/{subject_slug}/{today}-investigation.md",
        "Level 4: Meta-Pattern Synthesis": f"distillations/{subject_slug}/{today}-meta-patterns.md",
        "Level 4: Paradigm Extraction": f"distillations/{subject_slug}/{today}-paradigm-extraction.md",
    }
    strategic_file = f"backlog/{subject_slug}/{today}-paradigm-shift-{intent_slug}.md"

    for tool, filepath in artifact_map.items():
        if any(tool.lower() in t.lower() for t in tool_list):
            os.makedirs(os.path.dirname(filepath), exist_ok=True)
            with open(filepath, "w") as f:
                f.write(f"# {tool}\n\nSubject: {target}\nIntent: {intent}\nClues: {clues}\n\n*Auto-generated by Copilot agent for Issue investigation.*\n")
            artifacts.append(filepath)
    os.makedirs(os.path.dirname(strategic_file), exist_ok=True)
    with open(strategic_file, "w") as f:
        f.write(f"# Strategic Backlog\n\nSubject: {target}\nIntent: {intent}\nClues: {clues}\n\n*Auto-generated by Copilot agent for Issue investigation.*\n")
    artifacts.append(strategic_file)

    os.makedirs("catalogue", exist_ok=True)
    manifest_path = "catalogue/manifest.json"
    # Load manifest, ensure it's a list
    manifest = []
    if os.path.exists(manifest_path):
        with open(manifest_path) as f:
            manifest_loaded = json.load(f)
            if isinstance(manifest_loaded, list):
                manifest = manifest_loaded
            else:
                manifest = [manifest_loaded]
    # Add new entries -- FIXED!
    for af in artifacts:
        manifest.append({
            "issue": issue_number,
            "target": target,
            "depth": depth,
            "intent": intent,
            "artifact": af,
            "created": today
        })
    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2)
    # Update catalogue/index.md
    with open("catalogue/index.md", "w") as f:
        f.write("# Wisdom Library Catalogue Index\n\n")
        for entry in manifest:
            f.write(f"- [{entry['artifact']}]({entry['artifact']}) — Issue #{entry['issue']}, Target: {entry['target']}, Intent: {entry['intent']}, Date: {entry['created']}\n")

if __name__ == "__main__":
    main()
