import os
import json
import re
from datetime import datetime

def slugify(text):
    return re.sub('[^a-zA-Z0-9_-]', '', text.replace(" ", "-").lower())[:32]

def main():
    today = datetime.now().strftime('%Y-%m-%d')
    target = os.environ.get("AGENT_TARGET", "unknown-repo")
    depth = os.environ.get("AGENT_DEPTH", "Atomic")
    tools = os.environ.get("AGENT_TOOLS", "")
    intent = os.environ.get("AGENT_INTENT", "general-investigation")
    clues = os.environ.get("AGENT_CLUES", "")
    issue_number = os.environ.get("ISSUE_NUMBER", "1")

    tool_list = [x.strip() for x in tools.split(",") if x.strip()]

    subject_slug = slugify(target.split('/')[-1]) or 'unknown'
    intent_slug = slugify(intent) or 'unknown'

    artifacts = []
    
    # Load the artifact map from the external configuration file
    with open("config/artifact_map.json") as f:
        artifact_map = json.load(f)

    # Process each tool selected in the issue
    for tool_name in tool_list:
        if tool_name in artifact_map:
            config = artifact_map[tool_name]
            
            # Format the output path with dynamic values
            filepath = config["output_path"].format(
                subject_slug=subject_slug,
                today=today
            )
            
            os.makedirs(os.path.dirname(filepath), exist_ok=True)
            with open(filepath, "w") as f:
                f.write(f"# {tool_name}\n\nSubject: {target}\nIntent: {intent}\nClues: {clues}\n\n*Auto-generated by Copilot agent for Issue investigation.*\n")
            artifacts.append(filepath)

    # Preserve the logic for the strategic file
    strategic_file = f"backlog/{subject_slug}/{today}-paradigm-shift-{intent_slug}.md"
    os.makedirs(os.path.dirname(strategic_file), exist_ok=True)
    with open(strategic_file, "w") as f:
        f.write(f"# Strategic Backlog\n\nSubject: {target}\nIntent: {intent}\nClues: {clues}\n\n*Auto-generated by Copilot agent for Issue investigation.*\n")
    artifacts.append(strategic_file)

    # Create a list of manifest entries for the current run only
    run_manifest_entries = []
    for af in artifacts:
        run_manifest_entries.append({
            "issue": issue_number,
            "target": target,
            "depth": depth,
            "intent": intent,
            "artifact": af,
            "created": today
        })

    # Write the current run's manifest entries to a new fragment file
    if run_manifest_entries:
        fragment_dir = "catalogue/fragments"
        os.makedirs(fragment_dir, exist_ok=True)
        fragment_path = os.path.join(fragment_dir, f"issue-{issue_number}.json")
        with open(fragment_path, "w") as f:
            json.dump(run_manifest_entries, f, indent=2)

if __name__ == "__main__":
    main()
