import os
import json
import re
from datetime import datetime

def parse_agent_payload(issue_body):
    m = re.search(r'```yaml\nagent_prompt:(.*?)```', issue_body, re.DOTALL)
    if not m:
        raise Exception("No agent_payload block found.")

    yaml_payload = m.group(1)
    # Minimal naive YAML to dict parser for this structured block:
    result = {}
    for line in yaml_payload.split('\n'):
        line = line.strip()
        if ':' in line:
            k, v = line.split(':', 1)
            result[k.strip()] = v.strip().strip('"')
    return result

def slugify(text):
    return re.sub('[^a-zA-Z0-9_-]', '', text.replace(" ", "-").lower())[:32]

def main():
    issue_body = os.environ.get('ISSUE_BODY', '')
    today = datetime.now().strftime('%Y-%m-%d')
    if not issue_body:
        raise Exception("No ISSUE_BODY env variable provided.")

    payload = parse_agent_payload(issue_body)
    # Extract details
    target = payload.get('target', 'unknown-repo')
    depth = payload.get('depth', 'Atomic')
    tools = [x.strip() for x in payload.get('tools', 'Level 1').split(',') if x.strip()]
    intent = payload.get('intent', 'general-investigation')
    clues = payload.get('clues', '')

    subject_slug = slugify(target.split('/')[-1]) or 'unknown'
    intent_slug = slugify(intent) or 'unknown'

    artifacts = []
    
    # Mapping of levels to folders and filenames
    artifact_map = {
        "Level 1: Hard Architecture Mapping": f"analyses/{subject_slug}/{today}-hard-architecture-mapping.md",
        "Level 2: Decision Forensics": f"atomic/{subject_slug}/{today}-decision-forensics.md",
        "Level 2: Anti-Library Extraction": f"atomic/{subject_slug}/{today}-anti-library.md",
        "Level 3: Vision Alignment": f"atomic/{subject_slug}/{today}-vision-alignment.md",
        "Level 3: Process Memory": f"process_memory/{subject_slug}/{today}-investigation.md",
        "Level 4: Meta-Pattern Synthesis": f"distillations/{subject_slug}/{today}-meta-patterns.md",
        "Level 4: Paradigm Extraction": f"distillations/{subject_slug}/{today}-paradigm-extraction.md",
    }
    # Strategic Backlog filler
    strategic_file = f"backlog/{subject_slug}/{today}-paradigm-shift-{intent_slug}.md"

    # Generate artifacts
    for tool, filepath in artifact_map.items():
        if any(tool.lower() in t.lower() for t in tools):
            os.makedirs(os.path.dirname(filepath), exist_ok=True)
            with open(filepath, "w") as f:
                f.write(f"# {tool}\n\nSubject: {target}\nIntent: {intent}\nClues: {clues}\n\n*Auto-generated by Copilot agent for Issue investigation.*\n")
            artifacts.append(filepath)
    # Always create strategic backlog file
    os.makedirs(os.path.dirname(strategic_file), exist_ok=True)
    with open(strategic_file, "w") as f:
        f.write(f"# Strategic Backlog\n\nSubject: {target}\nIntent: {intent}\nClues: {clues}\n\n*Auto-generated by Copilot agent for Issue investigation.*\n")
    artifacts.append(strategic_file)

    # Update catalogue/manifest.json
    os.makedirs("catalogue", exist_ok=True)
    manifest_path = "catalogue/manifest.json"
    manifest = []
    if os.path.exists(manifest_path):
        with open(manifest_path) as f:
            manifest = json.load(f)
    manifest.extend({
        "issue": os.environ.get("ISSUE_NUMBER"),
        "target": target,
        "depth": depth,
        "intent": intent,
        "artifact": af,
        "created": today
    } for af in artifacts)
    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2)
    # Update catalogue/index.md
    with open("catalogue/index.md", "w") as f:
        f.write("# Wisdom Library Catalogue Index\n\n")
        for entry in manifest:
            f.write(f"- [{entry['artifact']}]({entry['artifact']}) — Issue #{entry['issue']}, Target: {entry['target']}, Intent: {entry['intent']}, Date: {entry['created']}\n")

if __name__ == "__main__":
    main()
