name: "🧠 Conceptual Investigation Intake"
description: "Initiate an autonomous AI investigation to distill wisdom, decisions, or architecture."
title: "[Intake]: "
labels: ["investigation", "autonomous-agent"]
body:
  - type: markdown
    attributes:
      value: |
        # Project Wisdom Intake
        *This form triggers an autonomous agent investigation.*
        
        **Guidance:** The quality of the output depends entirely on the quality of your **Context**. Don't just say *what* to look at; explain *why* it matters to you.

  - type: dropdown
    id: analysis-type
    attributes:
      label: Investigation Depth
      description: How deep should the agent go?
      options:
        - "Atomic (Quick check, single specific question)"
        - "Long-Form (Deep distillation, multi-file synthesis)"
    validations:
      required: true

  - type: input
    id: target
    attributes:
      label: Target (Repository or Document)
      description: Link to the repo, PR, or document to analyze.
      placeholder: "https://github.com/my-org/my-repo"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: The "Why" & Strategic Context
      description: |
        CRITICAL: What is your core uncertainty? What decision are you trying to make? What is your frustration?
        (The agent uses this to filter millions of lines of code. Be subjective!)
      placeholder: |
        "I am worried that our Auth service is becoming too complex for the new mobile team. I want to know if the original architects anticipated this pain..."
    validations:
      required: true

  - type: checkboxes
    id: menu-items
    attributes:
      label: The Wisdom Ladder (Methodologies)
      description: Which analysis tools should the agent apply?
      options:
        - label: "Level 1: Hard Architecture Mapping (The Structure)"
        - label: "Level 2: Decision Forensics (The History/Commit Logs)"
        - label: "Level 2: Anti-Library Extraction (What failed/was discarded?)"
        - label: "Level 3: Vision Alignment (Does code match intent?)"
        - label: "Level 3: Process Memory (Capture the rationale)"
        - label: "Level 4: Meta-Pattern Synthesis (Recurring themes)"
        - label: "Level 4: Paradigm Extraction (Mental Models & Shifts)"
    validations:
      required: true

  - type: textarea
    id: special-requests
    attributes:
      label: Special Requests
      description: Any specific focus areas? (e.g., "Focus on the payment module")
