name: "🧠 Conceptual Investigation Intake"
description: "Initiate an autonomous AI investigation. Point and Shoot."
title: "[Intake]: "
labels: ["investigation", "autonomous-agent"]
body:
  - type: markdown
    attributes:
      value: |
        # Project Wisdom Intake
        *This form triggers an autonomous agent investigation.*
        
        **Action:** Fill this form and **Assign to Copilot** to start.

  - type: dropdown
    id: analysis-type
    attributes:
      label: Investigation Depth
      options:
        - "Atomic (Quick check)"
        - "Long-Form (Deep distillation)"
    validations:
      required: true

  - type: input
    id: target
    attributes:
      label: Target Repository URL
      placeholder: "https://github.com/my-org/my-repo"
    validations:
      required: true

  - type: checkboxes
    id: menu-items
    attributes:
      label: Methodology (The Wisdom Ladder)
      options:
        - label: "Level 1: Hard Architecture Mapping"
        - label: "Level 2: Decision Forensics"
        - label: "Level 2: Anti-Library Extraction"
        - label: "Level 3: Vision Alignment"
        - label: "Level 3: Process Memory"
        - label: "Level 4: Meta-Pattern Synthesis"
        - label: "Level 4: Paradigm Extraction"
    validations:
      required: true

  - type: textarea
    id: intent
    attributes:
      label: Intent / Strategic Context (Optional)
      description: Leave blank to let the Agent infer intent from the Target.
      placeholder: "e.g. Audit for security risks"
    validations:
      required: false

  - type: textarea
    id: special-requests
    attributes:
      label: Special Observations (Optional)
      placeholder: "e.g. I noticed the auth module is weird."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ```yaml
        agent_prompt:
          role: System Owner Agent
          trigger: Assignment detected
          action: Execute Wisdom Ladder Protocol
          inputs:
            target: ${{ target }}
            depth: ${{ analysis-type }}
            tools: ${{ menu-items }}
            intent: ${{ intent }}
            clues: ${{ special-requests }}
          instructions:
            1. Profile the [target].
            2. If [intent] is empty, infer it from [tools] and [target].
            3. Execute the selected [tools].
            4. Generate 'process_memory' (JSON) and Analysis Artifacts.
            5. Submit PR.
        ```
