name: "🧠 Conceptual Investigation Intake"
description: "Initiate an autonomous AI investigation to distill wisdom, decisions, or architecture."
title: "[Intake]: "
labels: ["investigation", "autonomous-agent"]
body:
  - type: markdown
    attributes:
      value: |
        # Project Wisdom Intake
        *This form initiates an autonomous investigation.*
        
        **Instructions:** You do not need to use technical jargon. Just tell us what is happening, what you are worried about, and what you need to decide.

  - type: dropdown
    id: analysis-type
    attributes:
      label: Investigation Depth
      description: How deep should the agent go?
      options:
        - "Atomic (Quick check, single specific question)"
        - "Long-Form (Deep distillation, multi-file synthesis)"
    validations:
      required: true

  - type: input
    id: target
    attributes:
      label: Target (Repository or Document)
      placeholder: "https://github.com/my-org/my-repo"
    validations:
      required: true

  # --- The "Strategic Context" Elicitation Section ---
  
  - type: textarea
    id: trigger
    attributes:
      label: 1. The Trigger (What happened?)
      description: What event, meeting, or observation prompted this request?
      placeholder: "e.g., 'We are preparing for a security audit,' or 'I noticed the team is struggling to add new features.'"
    validations:
      required: true

  - type: textarea
    id: fear
    attributes:
      label: 2. The Uncertainty (What are you worried about?)
      description: What is your gut feeling or fear about this system? What might be wrong?
      placeholder: "e.g., 'I am worried the original auth code relies too much on session cookies,' or 'I feel like we are drifting away from our mobile-first vision.'"
    validations:
      required: true

  - type: textarea
    id: decision
    attributes:
      label: 3. The Goal (What do you need to decide?)
      description: What action depends on this answer?
      placeholder: "e.g., 'I need to decide whether to refactor this module or rewrite it completely.'"
    validations:
      required: true

  # -----------------------------------------------------

  - type: checkboxes
    id: menu-items
    attributes:
      label: The Wisdom Ladder (Methodologies)
      description: Select the tools the agent should use (Agent will refine this based on your context).
      options:
        - label: "Level 1: Hard Architecture Mapping (The Structure)"
        - label: "Level 2: Decision Forensics (The History/Commit Logs)"
        - label: "Level 2: Anti-Library Extraction (What failed/was discarded?)"
        - label: "Level 3: Vision Alignment (Does code match intent?)"
        - label: "Level 3: Process Memory (Capture the rationale)"
        - label: "Level 4: Meta-Pattern Synthesis (Recurring themes)"
        - label: "Level 4: Paradigm Extraction (Mental Models & Shifts)"
    validations:
      required: true

  - type: textarea
    id: special-requests
    attributes:
      label: Special Requests
      description: Any specific focus areas? (e.g., "Focus on the payment module")
