name: "🧠 Conceptual Investigation Intake"
description: "Initiate an autonomous AI investigation. You point, the Agent reasons."
title: "[Intake]: "
labels: ["investigation", "autonomous-agent"]
body:
  - type: markdown
    attributes:
      value: |
        # Project Wisdom Intake
        *This form triggers an autonomous agent investigation.*

  - type: dropdown
    id: analysis-type
    attributes:
      label: Investigation Depth
      options:
        - "Atomic (Quick check, specific question)"
        - "Long-Form (Deep distillation, multi-file synthesis)"
    validations:
      required: true

  - type: input
    id: target
    attributes:
      label: Target (Repository or Document)
      placeholder: "https://github.com/my-org/my-repo"
    validations:
      required: true

  - type: checkboxes
    id: menu-items
    attributes:
      label: The Wisdom Ladder (Methodologies)
      description: Select the tools. The Agent will determine how to apply them.
      options:
        - label: "Level 1: Hard Architecture Mapping (The Structure)"
        - label: "Level 2: Decision Forensics (The History)"
        - label: "Level 2: Anti-Library Extraction (The Failures)"
        - label: "Level 3: Vision Alignment (Intent vs. Reality)"
        - label: "Level 3: Process Memory (The Rationale)"
        - label: "Level 4: Meta-Pattern Synthesis (The Patterns)"
        - label: "Level 4: Paradigm Extraction (The Mental Models)"
    validations:
      required: true

  - type: textarea
    id: intent
    attributes:
      label: Strategic Intent / Context (Optional)
      description: Add context only if you have a specific goal. Otherwise, the Agent will infer intent from the code and tools selected.
      placeholder: "Optional: 'We are auditing for security risks' or 'I want to understand the coupling.'"
    validations:
      required: false

  - type: textarea
    id: special-requests
    attributes:
      label: Special Requests / Observations (Optional)
      description: Specific files or issues to focus on?
      placeholder: "e.g., 'Focus on the user_auth.go file'"
    validations:
      required: false
